spring.application.name = dailymotionminer
server.port=8081
logging.level.aiss.dailymotionminer.controller=DEBUG
# Global variables

dailymotionminer.maxVideos=10
dailymotionminer.maxTags=2
dailymotionminer.maxPages=2

videominer.uri = "http://localhost:8080/videominer/channel"