spring.application.name = dailymotionminer
server.port=8081
logging.level.aiss.dailymotionminer.controller=DEBUG
# Global variables

dailymotionminer.maxVideos=10
dailymotionminer.maxComments=10

videominer.uri = "http://localhost:8080/videominer/channel"