# APPLICATION CORE CONFIGURATION

spring.application.name = dailymotionminer
server.port=8081

# Set to DEBUG for tracing of the Controller layer
logging.level.aiss.dailymotionminer.controller=DEBUG

# Global variables

dailymotionminer.maxVideos=10
dailymotionminer.maxTags=2
dailymotionminer.maxPages=2

videominer.uri = ${VIDEOMINER_URL:http://localhost:8080/videominer/api/v1/channels}